//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp2db_conn.db_context
{
    using System;
    using System.Collections.Generic;
    
    public partial class mvctable
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public int mobile { get; set; }
        public string dept { get; set; }
        public int salry { get; set; }
        public int zip { get; set; }
    }
}
